# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
# baseurl: "/emeliatang"
url: "http://github.io"
twitter_username: 
github_username:  emeliatang

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - "bower_components"
  - "node_modules"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gruntfile.coffee"
  - "package.json"
  - "Rakefile"
  - "README.md"

include:
  - .nojekyll
